user repository created with find by username method
wolox-training/mr-java pull request #7
Opened 2019-05-03 13:33 UTC by rabinovichm

Trello card: https://trello.com/c/tzpOpeVV/21-crear-un-repositorio-de-users

2019-05-03 14:06 UTC, Jimenarosello requested changes
One small change and it's good to go 😄

2019-05-03 14:06 UTC, Jimenarosello commented on training/src/main/java/wolox/training/repositories/UserRepository.java
> +public interface UserRepository extends CrudRepository {
I think you need to add the types in CrudRepository (CrudRepository<User, Integer>).

2019-05-06 16:10 UTC, zeminlu approved these changes
Looks good! 👍

2019-05-06 18:44 UTC, Jimenarosello approved these changes

2019-05-09 16:21 UTC, merged