User controller with CRUD operations
wolox-training/mr-java pull request #8
Opened 2019-05-03 15:21 UTC by rabinovichm

Trello card: https://trello.com/c/Grbe1chv/22-crear-user-controller-con-las-operaciones-crud-de-user

2019-05-03 18:13 UTC, Jimenarosello requested changes
Just a few details 😄

2019-05-03 18:13 UTC, Jimenarosello commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @GetMapping("/user/{id}")
Change the base path so that it's the same for all mappings (for example this one should be "/users/{id}"). The same goes for all mappings below :)

2019-05-03 18:13 UTC, Jimenarosello commented on training/src/main/java/wolox/training/controllers/UserController.java
> +        if(id != user.getId()){
Use .equals() instead of != for non primitive types

2019-05-06 16:12 UTC, zeminlu requested changes
Same thing Jime requested, uri paths :)

2019-05-06 19:56 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @GetMapping("/user/{id}")
I've made this change on the postman branch before seeing this comment. Should I change it here too?

2019-05-09 21:00 UTC, zeminlu approved these changes

2019-05-09 21:16 UTC, Jimenarosello approved these changes

2019-05-13 14:55 UTC, merged